### ISSUE TITLE
Feature request: add a -setup, consolidate Tomb1Main.json5 with Tomb1Main-runtime.json5

### ISSUE THREAD

**Issue by rr-** [LostArtefacts/Tomb1Main#149]
People can not be bothered to edit the JSONs so we have to provide a GUI for them.

**Comment by walkawayy** [comment]
Can this be closed now that the config tool has been released?

**Comment by rr-** [comment]
Yes. Eventually I'd like to move the entire config into the game UIs, but that's distant future.
