### ISSUE TITLE
Feature: Use 3D objects in overlay when 3D pickups are enabled

### ISSUE THREAD

**Issue by ANoDE85** [LostArtefacts/Tomb1Main#257]
Currently, Tomb1Main draws pickups in the overlay as sprites even when 3D pickups are enabled. Since the 3D objects are properly upscaled by the engine, the sprites don't look as good as the 3D objects.

Optionally, the pickup objects should rotate in the overlay like they do in more recent engine versions.

In case using the 3D objects for the overlays is not feasible, the 3D objects that are used as pickups could be rendered once (for example with a slight rotation) and cached, and used for drawing the pickup sprite instead.

**Comment by Richard-L** [comment]
Thought I'd add some content to look at regarding this.

Although I'm not 100% sure, I believe the idea stems from how the ECTS 1998 TR3 demo did it. I recorded some examples:

https://user-images.githubusercontent.com/4934209/150802383-2313536a-8ca4-4caa-b150-5da427a3f61f.mp4

https://user-images.githubusercontent.com/4934209/150802405-6adbba56-9f98-4e40-9e04-2d0df5392834.mp4

https://user-images.githubusercontent.com/4934209/150802413-184e231e-a96c-4ac4-97cc-78ed7bf19aa2.mp4

Arsunt had shown however that the feature is quite hit or miss https://youtu.be/iek73un3WA4
Source: https://discord.com/channels/218414493355606016/394838132643725314/833606389187215390

The animation was apparently scrapped in TR3, and replaced by overlays again, which however appear to stem from 3D data. Compare TR3 Oct 13, 1998 prototype:

https://user-images.githubusercontent.com/4934209/150803235-bfd8f8ec-1075-46df-8ce9-9d4ac4931b3a.mp4

Eventually OpenLara came around, and it seems the only available code now that can do this. Compare XProger's solution for more complex cases such as quick successive multi-pickups: http://xproger.info/projects/OpenLara/shots/pickup_overview.mp4

**Comment by rr-** [comment]
We are already doing this with the new inventory overlays where we display two 3D scenes on top of each other. The trick is to clear the depth buffer (while keeping the depth testing enabled).

**Comment by Richard-L** [comment]
Sounds great. Excited to see.
