### ISSUE TITLE
Screenshot bugs during FMVs

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/Tomb1Main#445]
It looks like you can crash the game if you hit the PRINT key for a screenshot during the FMVs before the title screen. Tried both `.RPL` and `.FMV`:

![image](https://user-images.githubusercontent.com/4934209/154802438-7eee8902-29a9-469b-83be-05e61fe2a4a2.png)

Curiously during a later FMV (I tried "LIFT"), the PRINT screen will fail first but the game stays alive, and consequent PRINT hits will take screenshots as expected.
![20220219_141339_Cut_Scene_1](https://user-images.githubusercontent.com/4934209/154802464-d2b3ea1b-bbfe-4d10-b9c6-5b43758e60ef.png)

**Comment by rr-** [comment]
Works for me

![20220219_213339_Level_-1](https://user-images.githubusercontent.com/1045476/154819913-67521fdd-24dd-4e94-b764-f7c21f6ec5c9.jpg)
![20220219_213339_Level_-1_2](https://user-images.githubusercontent.com/1045476/154819914-cb42f88a-3051-4d99-9eb5-4cebf4ca5f8d.jpg)
![20220219_213340_Level_-1](https://user-images.githubusercontent.com/1045476/154819915-d9452ba4-21f7-4738-a9ff-1babaa54a1a5.jpg)
![20220219_213340_Level_-1_2](https://user-images.githubusercontent.com/1045476/154819916-c5fad791-bef7-4102-9799-a04c3fc617af.jpg)
![20220219_213341_Level_-1](https://user-images.githubusercontent.com/1045476/154819917-e69858d6-6b97-4dd2-822d-5e0f715cda30.jpg)
![20220219_213341_Level_-1_2](https://user-images.githubusercontent.com/1045476/154819919-7f4cb317-2354-43c4-82b0-77c046c859e1.jpg)
![20220219_213341_Level_-1_3](https://user-images.githubusercontent.com/1045476/154819920-c9a21480-32c8-4ed7-ab17-f12915d5e277.jpg)
![20220219_213341_Level_-1_4](https://user-images.githubusercontent.com/1045476/154819921-d9c449a4-dfff-471e-a124-11654b979030.jpg)
![20220219_213341_Level_-1_5](https://user-images.githubusercontent.com/1045476/154819923-a6fc8b66-ddec-4198-900b-8d269b5a1c3c.jpg)
![20220219_213342_Level_-1](https://user-images.githubusercontent.com/1045476/154819924-7a5bb94b-0600-4eaf-b92f-d22b6749b4cd.jpg)
![20220219_213342_Level_-1_2](https://user-images.githubusercontent.com/1045476/154819925-66db3cbb-7cea-401f-9e14-705cb2b7b7ec.jpg)
![20220219_213343_Level_-1](https://user-images.githubusercontent.com/1045476/154819927-43907805-ff99-46f4-9d1e-f2fb9b790b93.jpg)
![20220219_213343_Level_-1_2](https://user-images.githubusercontent.com/1045476/154819928-6fd5eb91-e5be-489b-a46b-1ce05ba5c51f.jpg)
![20220219_213343_Level_-1_3](https://user-images.githubusercontent.com/1045476/154819929-3cef27d5-9fb7-4c0c-a641-afeb8417cfb5.jpg)
![20220219_213343_Level_-1_4](https://user-images.githubusercontent.com/1045476/154819930-c28411de-c733-4a54-866f-1451f30cc165.jpg)
![20220219_213351_Title](https://user-images.githubusercontent.com/1045476/154819932-b1ec6653-1d1e-4dd3-ab5d-d18d81497afc.jpg)
![20220219_213351_Title_2](https://user-images.githubusercontent.com/1045476/154819933-f731af68-cd9f-40a0-82ca-16c4940a7aa1.jpg)
![20220219_213351_Title_3](https://user-images.githubusercontent.com/1045476/154819934-4d885520-ac1b-458f-a0a8-3161f6fbd29a.jpg)
![20220219_213352_Title](https://user-images.githubusercontent.com/1045476/154819936-2408ddd6-4b6c-4e3f-b918-62da6e044c5c.jpg)
![20220219_213404_Title](https://user-images.githubusercontent.com/1045476/154819937-210eb6de-d01e-42be-bfff-ed7694ee9004.jpg)
![20220219_213404_Title_2](https://user-images.githubusercontent.com/1045476/154819938-849ce171-8be9-41a0-afc2-303c248c15e2.jpg)
![20220219_213404_Title_3](https://user-images.githubusercontent.com/1045476/154819940-428b2fdf-b2cd-41d7-a63d-ac9d870e3044.jpg)
![20220219_213405_Title](https://user-images.githubusercontent.com/1045476/154819941-c1ee87a9-4136-4674-a1f1-8da7b1d43dbd.jpg)
![20220219_213418_Cut_Scene_1](https://user-images.githubusercontent.com/1045476/154819943-d504d0a9-adbe-42b9-8ace-7ad5fe05eed7.jpg)
![20220219_213418_Cut_Scene_1_2](https://user-images.githubusercontent.com/1045476/154819945-02206570-ce86-4cfc-91c0-1ea42e09406a.jpg)
![20220219_213418_Cut_Scene_1_3](https://user-images.githubusercontent.com/1045476/154819946-4467c22e-0889-46a3-b43e-84457051720d.jpg)
![20220219_213419_Cut_Scene_1](https://user-images.githubusercontent.com/1045476/154819949-57d599ec-ee2d-4206-b65d-21e872a9fc13.jpg)

**Comment by Richard-L** [comment]
Huh, strange. Can anyone else reproduce this?

**Comment by Rapora9** [comment]
> Huh, strange. Can anyone else reproduce this?

I tested _core_, _cafe_ and _snow_ (both avi and rpl), and screenshotting with `windows key + prt sc` (laptop) works just fine.

(Slightly offtopic: screenshotting during pictures (eidos, credits) results in a black screenshot. Should this be an issue or not?)

**Comment by Richard-L** [comment]
@Rapora9 Isn't that Window's native command for screenshot taking? I meant TR1M's own function where it saves to png or jpg in the base folder.

**Comment by Rapora9** [comment]
Hmm, I see. With that command I get a screenshot to both in the game's own folder and Window's folder too. If I only press `prt sc` during _Eidos_, _core_ or _cafe_, then there is a chance of the game crashing without an error message.

**Comment by Richard-L** [comment]
Okay yeah that's the same behaviour then. PNG here too. Would be surprised if it made a difference.

**Comment by atombraiderfan** [comment]
T1M also crashes for me when taking .PNG format screenshots of the edios screen and all startup FMVs.  It doesn't crash when I take screenshots in .JPG format instead.

**Comment by Richard-L** [comment]
Okay so perhaps it is related to the format after all

**Comment by carlo-bramini** [comment]
The engine crashes because here:

https://github.com/rr-/Tomb1Main/blob/9f0675f53ae20fc73a1522308ff6d4f10177ac20/src/game/shell.c#L46

`g_CurrentLevel` is `-1` and `snprintf()` crashes in a point where it evaluates the length of that parameter.
