### ISSUE TITLE
Feature request: jump twists from TR2+

### ISSUE THREAD

**Issue by Eddy7454** [LostArtefacts/Tomb1Main#88]

**Comment by lahm86** [comment]
Hi @ajtudela. Would you be able to provide the translation for the new config entry for this feature?

```json
"enable_jump_twists": {
  "Title": "Jump twists",
  "Description": "Enables TR2+ style jump twists and somersaults i.e. press roll during jump and swan dive animations."
}
```

**Comment by ajtudela** [comment]
Sorry for the delay, I've been on holidays.

Here is the translation:

```json
"enable_jump_twists": {
  "Title": "Giros al saltar",
  "Description": "Habilita los giros al saltar y saltos mortales al estilo TR2+, es decir, presione rodar durante las animaciones del salto y salto del cisne"
}
```

**Comment by lahm86** [comment]
> Sorry for the delay, I've been on holidays.
> 
> Here is the translation:
> 
> ```json
> "enable_jump_twists": {
>   "Title": "Giros al saltar",
>   "Description": "Habilita los giros al saltar y saltos mortales al estilo TR2+, es decir, presione rodar durante las animaciones del salto y salto del cisne"
> }
> ```

Thank you :)
